title: Heitor Gouvêa
url: "https://heitorgouvea.me"
baseurl: ""
markdown: kramdown
author: "@GouveaHeitor"
keywords: "Heitor Gouvêa, Information Security, Bug Bounty, Independent, Research, Write Up"

tracking_id: #

footer: yes
footer_url: "https://heitorgouvea.me"
footer_text: "Copyright © 2019 Heitor Gouvêa"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about"
